#ifndef CONFIG_H
#define CONFIG_H

#define PROGRAM_TITLE "OpenPPS"

#define DEFAULT_RESOLUTION_HORIZONTAL 1280
#define DEFAULT_RESOLUTION_VERTICAL 800

#define DEFAULT_TRACE_LOG_LEVEL LOG_WARNING
#define HIDE_CURSOR true
#define DEFAULT_FRAMERATE 60

#endif